### PR TITLE
show points after players name

### PR DESCRIPTION
**Pull request by eboyfriends**

### CODE REVIEW

**Comment by K4ryuu** [comment]
Greetings,
Sadly it's not a planned feature for now, but I appreciate your request.

Best Regards,
K4ryuu

**Comment by K4ryuu** [comment]
I've looked into your code and I realised you add the point to the killed player's name. lmao
I thought you wanna add to the real player's name 🤣

**Comment by eboyfriends** [comment]
> I've looked into your code and I realised you add the point to the killed player's name. lmao
> 
> I thought you wanna add to the real player's name 🤣 


yeah, some server owner wanted it like that. said why not and sent er. appreciate accepting the req.

**Comment by K4ryuu** [comment]
Well this plugin gon' be archived today, but keep on going on the new version :P

**Pull request merged**
